title: Agustin Lorenzo
url: "https://ankitsultana.com"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "CV"
   link: "resume.pdf"
 - name: "Portfolio"
   link: "portfolio"
 - name: "Contact"
   link: "contact"
